# Read Image and conver to numpy for machine learning

In [ ]:
from PIL import Image
from PIL import ImageColor
import numpy as np
import glob

In [81]:
# Import all images
path_land = './tmp'
path_buld = './tmp_bld'

land_imgs = []
buld_imgs = []
for filename in glob.glob('./tmp/*.png'):
    land_img = Image.open(filename)
    land_imgs.append(land_img)
land_imgs = land_imgs[:-1]    
for filename in glob.glob('./tmp_bld/*.png'):
    buld_img = Image.open(filename)
    buld_imgs.append(buld_img)


print(len(land_imgs))
print(len(buld_imgs))
        

65
65


In [74]:
h_colorcode = ['#FFFFFF','#FF7E7E', '#FF5A5A', '#FF2424', '#FF0000', '#DB0000', '#B70000',
               '#A50000', '#810000', '#FF0080', '#5D0000']
h_colorrgb = []
for i in h_colorcode:
    rgb = ImageColor.getcolor(i, 'RGB')
    h_colorrgb.append(rgb)
h_dict = {}
for k, v in enumerate(h_colorrgb):
    h_dict[v] = k
    print(type(v))
print(h_dict)

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
{(255, 255, 255): 0, (255, 126, 126): 1, (255, 90, 90): 2, (255, 36, 36): 3, (255, 0, 0): 4, (219, 0, 0): 5, (183, 0, 0): 6, (165, 0, 0): 7, (129, 0, 0): 8, (255, 0, 128): 9, (93, 0, 0): 10}


In [82]:
# Convert image to numpy
def img_to_np(imgs):
    '''
    Convert image file to numpy array
    Input: list of images / Output: array of array
    '''
    np_list = []
    for img in imgs:
        img.size
        tmp = np.asarray(img)
        np_list.append(tmp)
    nps = np.asarray(np_list)    
    
    return nps
land_arrays = img_to_np(land_imgs)
buld_arrays = img_to_np(buld_imgs)
print(land_arrays.shape)
print(buld_arrays.shape)

(65, 512, 512, 4)
(65, 512, 512, 4)


In [117]:
# Add height column using color code
   
def height_pixel(imgs):
    '''
    Add height value using color code of by each pixel
    Input: array of array / Output: array of array
    '''
    rowx4 = imgs.reshape(17039360, 4)
    #print(rowx4)
    rowx3 = rowx4[:, :3]
    array_h = rowx3[:,0]/255
    array_h[array_h == 1] = 0
    array_h= array_h.reshape(17039360,1)
    rowx4h = np.hstack([rowx3, array_h])
    height_pts = array_h.reshape(65, 512, 512, 1)
    
    #print((np.unique(rowx3, axis = 0)))
    #unique, counts = np.unique(rowx3[:,0], return_counts = True, axis = 0)
    #red_count = np.asarray((unique, counts)).T
    #print(red_count[red_count[:, 1].argsort()][::-1])
    #h_list = [h_dict[tuple(i)] for i in rowx3]
    #print(h_list)
    
    return height_pts

heightPts = height_pixel(buld_arrays)
print(heightPts)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [ ]:
sample_pt = buld_arrays[0][0][0][:-1].reshape(3)
print(*sample_pt)
print('#{:02x}{:02x}{:02x}'.format(*sample_pt))

In [119]:
# Merge block and height array
def merge_np(block, height):
    '''
    Merge block and height data by each pixel
    Input: array of array, array of array / Output: array of array
    '''
    blockx4 = block.reshape(17039360, 4)
    blockx3 = blockx4[:, :3]
    heightx1 = height.reshape(17039360, 1)
    mergedx4 = np.hstack([blockx3, heightx1])
    merged_pts = mergedx4.reshape(65, 512, 512, 4)
    return merged_pts

mergedPts = merge_np(land_arrays, heightPts)
mergedPts

array([[[[255., 255., 255.,   0.],
         [255., 255., 255.,   0.],
         [255., 255., 255.,   0.],
         ...,
         [255., 255., 255.,   0.],
         [255., 255., 255.,   0.],
         [255., 255., 255.,   0.]],

        [[255., 255., 255.,   0.],
         [255., 255., 255.,   0.],
         [255., 255., 255.,   0.],
         ...,
         [255., 255., 255.,   0.],
         [255., 255., 255.,   0.],
         [255., 255., 255.,   0.]],

        [[255., 255., 255.,   0.],
         [255., 255., 255.,   0.],
         [255., 255., 255.,   0.],
         ...,
         [255., 255., 255.,   0.],
         [255., 255., 255.,   0.],
         [255., 255., 255.,   0.]],

        ...,

        [[255., 255., 255.,   0.],
         [255., 255., 255.,   0.],
         [255., 255., 255.,   0.],
         ...,
         [255., 255., 255.,   0.],
         [255., 255., 255.,   0.],
         [255., 255., 255.,   0.]],

        [[255., 255., 255.,   0.],
         [255., 255., 255.,   0.],
         [25

In [125]:
for k, v in enumerate(mergedPts):
    print(type(v))
    im = Image.fromarray(v)
    #im.save('./training/sample_training_{}'.format(str(k)))

<class 'numpy.ndarray'>


TypeError: Cannot handle this data type: (1, 1, 4), <f8

In [127]:
import torch

ModuleNotFoundError: No module named 'torch'